/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FunctionsRouteImport } from './routes/functions'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FunctionsIndexRouteImport } from './routes/functions/index'
import { Route as FunctionsDeclarationsRouteImport } from './routes/functions/declarations'
import { Route as FunctionsCallsRouteImport } from './routes/functions/calls'

const FunctionsRoute = FunctionsRouteImport.update({
  id: '/functions',
  path: '/functions',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionsIndexRoute = FunctionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FunctionsRoute,
} as any)
const FunctionsDeclarationsRoute = FunctionsDeclarationsRouteImport.update({
  id: '/declarations',
  path: '/declarations',
  getParentRoute: () => FunctionsRoute,
} as any)
const FunctionsCallsRoute = FunctionsCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => FunctionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/functions': typeof FunctionsRouteWithChildren
  '/functions/calls': typeof FunctionsCallsRoute
  '/functions/declarations': typeof FunctionsDeclarationsRoute
  '/functions/': typeof FunctionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/functions/calls': typeof FunctionsCallsRoute
  '/functions/declarations': typeof FunctionsDeclarationsRoute
  '/functions': typeof FunctionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/functions': typeof FunctionsRouteWithChildren
  '/functions/calls': typeof FunctionsCallsRoute
  '/functions/declarations': typeof FunctionsDeclarationsRoute
  '/functions/': typeof FunctionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comments'
    | '/functions'
    | '/functions/calls'
    | '/functions/declarations'
    | '/functions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comments'
    | '/functions/calls'
    | '/functions/declarations'
    | '/functions'
  id:
    | '__root__'
    | '/'
    | '/comments'
    | '/functions'
    | '/functions/calls'
    | '/functions/declarations'
    | '/functions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommentsRoute: typeof CommentsRoute
  FunctionsRoute: typeof FunctionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/functions': {
      id: '/functions'
      path: '/functions'
      fullPath: '/functions'
      preLoaderRoute: typeof FunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/': {
      id: '/functions/'
      path: '/'
      fullPath: '/functions/'
      preLoaderRoute: typeof FunctionsIndexRouteImport
      parentRoute: typeof FunctionsRoute
    }
    '/functions/declarations': {
      id: '/functions/declarations'
      path: '/declarations'
      fullPath: '/functions/declarations'
      preLoaderRoute: typeof FunctionsDeclarationsRouteImport
      parentRoute: typeof FunctionsRoute
    }
    '/functions/calls': {
      id: '/functions/calls'
      path: '/calls'
      fullPath: '/functions/calls'
      preLoaderRoute: typeof FunctionsCallsRouteImport
      parentRoute: typeof FunctionsRoute
    }
  }
}

interface FunctionsRouteChildren {
  FunctionsCallsRoute: typeof FunctionsCallsRoute
  FunctionsDeclarationsRoute: typeof FunctionsDeclarationsRoute
  FunctionsIndexRoute: typeof FunctionsIndexRoute
}

const FunctionsRouteChildren: FunctionsRouteChildren = {
  FunctionsCallsRoute: FunctionsCallsRoute,
  FunctionsDeclarationsRoute: FunctionsDeclarationsRoute,
  FunctionsIndexRoute: FunctionsIndexRoute,
}

const FunctionsRouteWithChildren = FunctionsRoute._addFileChildren(
  FunctionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommentsRoute: CommentsRoute,
  FunctionsRoute: FunctionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
