/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiteralsRouteImport } from './routes/literals'
import { Route as FunctionsRouteImport } from './routes/functions'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as BlockExpressionsRouteImport } from './routes/block-expressions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiteralsIndexRouteImport } from './routes/literals/index'
import { Route as FunctionsIndexRouteImport } from './routes/functions/index'
import { Route as LiteralsStringsRouteImport } from './routes/literals/strings'
import { Route as LiteralsNumbersRouteImport } from './routes/literals/numbers'
import { Route as FunctionsDeclarationsRouteImport } from './routes/functions/declarations'
import { Route as FunctionsCallsRouteImport } from './routes/functions/calls'

const LiteralsRoute = LiteralsRouteImport.update({
  id: '/literals',
  path: '/literals',
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionsRoute = FunctionsRouteImport.update({
  id: '/functions',
  path: '/functions',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockExpressionsRoute = BlockExpressionsRouteImport.update({
  id: '/block-expressions',
  path: '/block-expressions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteralsIndexRoute = LiteralsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LiteralsRoute,
} as any)
const FunctionsIndexRoute = FunctionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FunctionsRoute,
} as any)
const LiteralsStringsRoute = LiteralsStringsRouteImport.update({
  id: '/strings',
  path: '/strings',
  getParentRoute: () => LiteralsRoute,
} as any)
const LiteralsNumbersRoute = LiteralsNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => LiteralsRoute,
} as any)
const FunctionsDeclarationsRoute = FunctionsDeclarationsRouteImport.update({
  id: '/declarations',
  path: '/declarations',
  getParentRoute: () => FunctionsRoute,
} as any)
const FunctionsCallsRoute = FunctionsCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => FunctionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/block-expressions': typeof BlockExpressionsRoute
  '/comments': typeof CommentsRoute
  '/functions': typeof FunctionsRouteWithChildren
  '/literals': typeof LiteralsRouteWithChildren
  '/functions/calls': typeof FunctionsCallsRoute
  '/functions/declarations': typeof FunctionsDeclarationsRoute
  '/literals/numbers': typeof LiteralsNumbersRoute
  '/literals/strings': typeof LiteralsStringsRoute
  '/functions/': typeof FunctionsIndexRoute
  '/literals/': typeof LiteralsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/block-expressions': typeof BlockExpressionsRoute
  '/comments': typeof CommentsRoute
  '/functions/calls': typeof FunctionsCallsRoute
  '/functions/declarations': typeof FunctionsDeclarationsRoute
  '/literals/numbers': typeof LiteralsNumbersRoute
  '/literals/strings': typeof LiteralsStringsRoute
  '/functions': typeof FunctionsIndexRoute
  '/literals': typeof LiteralsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/block-expressions': typeof BlockExpressionsRoute
  '/comments': typeof CommentsRoute
  '/functions': typeof FunctionsRouteWithChildren
  '/literals': typeof LiteralsRouteWithChildren
  '/functions/calls': typeof FunctionsCallsRoute
  '/functions/declarations': typeof FunctionsDeclarationsRoute
  '/literals/numbers': typeof LiteralsNumbersRoute
  '/literals/strings': typeof LiteralsStringsRoute
  '/functions/': typeof FunctionsIndexRoute
  '/literals/': typeof LiteralsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/block-expressions'
    | '/comments'
    | '/functions'
    | '/literals'
    | '/functions/calls'
    | '/functions/declarations'
    | '/literals/numbers'
    | '/literals/strings'
    | '/functions/'
    | '/literals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/block-expressions'
    | '/comments'
    | '/functions/calls'
    | '/functions/declarations'
    | '/literals/numbers'
    | '/literals/strings'
    | '/functions'
    | '/literals'
  id:
    | '__root__'
    | '/'
    | '/block-expressions'
    | '/comments'
    | '/functions'
    | '/literals'
    | '/functions/calls'
    | '/functions/declarations'
    | '/literals/numbers'
    | '/literals/strings'
    | '/functions/'
    | '/literals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlockExpressionsRoute: typeof BlockExpressionsRoute
  CommentsRoute: typeof CommentsRoute
  FunctionsRoute: typeof FunctionsRouteWithChildren
  LiteralsRoute: typeof LiteralsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/literals': {
      id: '/literals'
      path: '/literals'
      fullPath: '/literals'
      preLoaderRoute: typeof LiteralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions': {
      id: '/functions'
      path: '/functions'
      fullPath: '/functions'
      preLoaderRoute: typeof FunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/block-expressions': {
      id: '/block-expressions'
      path: '/block-expressions'
      fullPath: '/block-expressions'
      preLoaderRoute: typeof BlockExpressionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literals/': {
      id: '/literals/'
      path: '/'
      fullPath: '/literals/'
      preLoaderRoute: typeof LiteralsIndexRouteImport
      parentRoute: typeof LiteralsRoute
    }
    '/functions/': {
      id: '/functions/'
      path: '/'
      fullPath: '/functions/'
      preLoaderRoute: typeof FunctionsIndexRouteImport
      parentRoute: typeof FunctionsRoute
    }
    '/literals/strings': {
      id: '/literals/strings'
      path: '/strings'
      fullPath: '/literals/strings'
      preLoaderRoute: typeof LiteralsStringsRouteImport
      parentRoute: typeof LiteralsRoute
    }
    '/literals/numbers': {
      id: '/literals/numbers'
      path: '/numbers'
      fullPath: '/literals/numbers'
      preLoaderRoute: typeof LiteralsNumbersRouteImport
      parentRoute: typeof LiteralsRoute
    }
    '/functions/declarations': {
      id: '/functions/declarations'
      path: '/declarations'
      fullPath: '/functions/declarations'
      preLoaderRoute: typeof FunctionsDeclarationsRouteImport
      parentRoute: typeof FunctionsRoute
    }
    '/functions/calls': {
      id: '/functions/calls'
      path: '/calls'
      fullPath: '/functions/calls'
      preLoaderRoute: typeof FunctionsCallsRouteImport
      parentRoute: typeof FunctionsRoute
    }
  }
}

interface FunctionsRouteChildren {
  FunctionsCallsRoute: typeof FunctionsCallsRoute
  FunctionsDeclarationsRoute: typeof FunctionsDeclarationsRoute
  FunctionsIndexRoute: typeof FunctionsIndexRoute
}

const FunctionsRouteChildren: FunctionsRouteChildren = {
  FunctionsCallsRoute: FunctionsCallsRoute,
  FunctionsDeclarationsRoute: FunctionsDeclarationsRoute,
  FunctionsIndexRoute: FunctionsIndexRoute,
}

const FunctionsRouteWithChildren = FunctionsRoute._addFileChildren(
  FunctionsRouteChildren,
)

interface LiteralsRouteChildren {
  LiteralsNumbersRoute: typeof LiteralsNumbersRoute
  LiteralsStringsRoute: typeof LiteralsStringsRoute
  LiteralsIndexRoute: typeof LiteralsIndexRoute
}

const LiteralsRouteChildren: LiteralsRouteChildren = {
  LiteralsNumbersRoute: LiteralsNumbersRoute,
  LiteralsStringsRoute: LiteralsStringsRoute,
  LiteralsIndexRoute: LiteralsIndexRoute,
}

const LiteralsRouteWithChildren = LiteralsRoute._addFileChildren(
  LiteralsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlockExpressionsRoute: BlockExpressionsRoute,
  CommentsRoute: CommentsRoute,
  FunctionsRoute: FunctionsRouteWithChildren,
  LiteralsRoute: LiteralsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
